# Changes here will be overwritten by Copier
_commit: 3249a90
_src_path: gh:alleninstitute/copier-pdm-npc
add_requirements_txt: true
author_email: ben.hardcastle@alleninstitue.org
author_fullname: Ben Hardcastle
author_username: bjhardcastle
build_doc: false
copyright_date: '2024'
copyright_holder: Allen Institute for Neural Dynamics
copyright_holder_email: ''
copyright_license: MIT
package_version: 0.1.0
project_description: Collection of MindScope Neuropixels packages, simplifying installation
    and keeping versions updated.
project_name: npc_utils
python_package_distribution_name: npc-utils
python_package_import_name: npc_utils
python_package_requires_python: '>=3.9'
repository_name: npc_utils
repository_namespace: AllenInstitute

